require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.1

  DisabledByDefault: true
  Exclude:
    - 'tmp/**/*'
    - 'bin/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

  SuggestExtensions: false
