version: '3.9'

services:
  psql:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5342:5342"

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: psql
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - psql
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - tatsumaki_bundle:/app/vendor/bundle

volumes:
  psql_data:
  tatsumaki_bundle:
